import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { build } from 'vite';

const require = createRequire(import.meta.url);

/**
 * Every client-side entry point svelte ships. Anything a compiled component or a user
 * module can pull in at runtime comes from one of these, so the union of their exports
 * bounds how large the svelte half of a client bundle can ever get.
 */
export const CLIENT_ENTRIES = [
	'svelte',
	'svelte/internal/client',
	'svelte/transition',
	'svelte/animate',
	'svelte/motion',
	'svelte/store',
	'svelte/reactivity',
	'svelte/reactivity/window',
	'svelte/easing',
	'svelte/legacy',
	'svelte/events',
	'svelte/attachments',
	'svelte/internal/disclose-version',
	'svelte/internal/flags/async',
	'svelte/internal/flags/legacy',
	'svelte/internal/flags/tracing'
];

const PREFIX = 'virtual:ceiling:';

/** @param {Record<string, string>} modules */
function virtual(modules) {
	return {
		name: 'ceiling-virtual',
		/** @param {string} id */
		resolveId: (id) => (id.startsWith(PREFIX) ? '\0' + id : null),
		/** @param {string} id */
		load: (id) => (id.startsWith('\0' + PREFIX) ? modules[id.slice(1)] : null)
	};
}

/**
 * Asks rollup what each entry point exports. Reading it back off the build output is
 * authoritative — parsing `index.js` by hand undercounts, because some names are
 * re-exported through chains the source text doesn't spell out.
 *
 * @param {string} root
 * @returns {Promise<Map<string, string[]>>}
 */
export async function collect_exports(root) {
	const modules = Object.fromEntries(
		CLIENT_ENTRIES.map((entry) => [PREFIX + entry, `export * from ${JSON.stringify(entry)};`])
	);

	const result = await build({
		root,
		configFile: false,
		logLevel: 'error',
		plugins: [virtual(modules)],
		build: {
			write: false,
			minify: false,
			rollupOptions: {
				input: Object.fromEntries(CLIENT_ENTRIES.map((e, i) => [`e${i}`, PREFIX + e])),
				preserveEntrySignatures: 'strict',
				output: { format: 'es' }
			}
		}
	});

	const output = (Array.isArray(result) ? result[0] : result).output;
	const map = new Map();

	for (const [i, entry] of CLIENT_ENTRIES.entries()) {
		const chunk = output.find((c) => c.type === 'chunk' && c.name === `e${i}`);
		map.set(
			entry,
			(chunk?.exports ?? []).filter((name) => name !== 'default')
		);
	}

	return map;
}

/**
 * Names `svelte/internal/client` re-exports out of its `dev/` directory.
 *
 * Svelte keeps its development-only helpers — `trace`, `inspect`, `hmr`, ownership
 * validation, source locations — in `src/internal/client/dev/`. A production compile
 * never emits calls to them, so counting them towards the ceiling inflates it by code
 * no shipped app can contain. Attribution comes from the export manifest rather than a
 * hand-written list, so it stays correct as the runtime changes.
 *
 * @param {string[]} all_exports every name rollup reports for svelte/internal/client
 * @returns {Set<string>}
 */
export function dev_exports(all_exports) {
	const index = path.join(
		path.dirname(require.resolve('svelte/package.json')),
		'src/internal/client/index.js'
	);
	const source = fs.readFileSync(index, 'utf-8');

	/** @type {Map<string, string>} */
	const origin = new Map();

	// the manifest is exclusively `export { a, b as c } from './path.js';` — no `export *`,
	// so every public name can be traced to the module that defines it
	for (const match of source.matchAll(/export\s*\{([^}]*)\}\s*from\s*'([^']+)'/g)) {
		for (const part of match[1].split(',')) {
			const name = part
				.trim()
				.split(/\s+as\s+/)
				.pop()
				?.trim();
			if (name) origin.set(name, match[2]);
		}
	}

	// if the manifest ever stops accounting for every export, say so instead of
	// silently mis-classifying — a wrong ceiling is worse than no ceiling
	const unattributed = all_exports.filter((name) => !origin.has(name));
	if (unattributed.length > 0) {
		throw new Error(
			`cannot attribute ${unattributed.length} export(s) of svelte/internal/client ` +
				`to a source module: ${unattributed.join(', ')}. ` +
				`scripts/ceiling.js needs updating.`
		);
	}

	return new Set(all_exports.filter((name) => /(^|\/)dev\//.test(origin.get(name) ?? '')));
}

/**
 * Builds an entry module that references every export by name and leaks the lot to
 * `globalThis`, so rollup cannot drop any of it.
 *
 * Named imports rather than `import * as ns` on purpose: a namespace object that escapes
 * forces rollup to materialise the namespace itself, which adds ~5kB of property tables
 * that no real app would ever ship. Naming each binding keeps the bound tight.
 *
 * @param {Map<string, string[]>} exports_by_entry
 * @param {Set<string>} skip dev-surface names to leave out of svelte/internal/client
 */
export function generate_entry(exports_by_entry, skip = new Set()) {
	const lines = [
		'// GENERATED by scripts/ceiling.js — do not edit.',
		'// Every export of every client-side svelte entry point, forced live.',
		'const sink = [];'
	];

	let count = 0;
	let skipped = 0;

	for (const [i, [entry, all]] of [...exports_by_entry].entries()) {
		// the dev surface only ever enters a bundle through internal/client
		const names = entry === 'svelte/internal/client' ? all.filter((name) => !skip.has(name)) : all;
		skipped += all.length - names.length;

		if (names.length === 0) {
			lines.push(`import ${JSON.stringify(entry)}; // side-effect only`);
			continue;
		}
		// alias everything: entry points overlap, and raw names would collide
		const spec = names.map((name) => `${name} as e${i}_${name}`).join(', ');
		lines.push(`import { ${spec} } from ${JSON.stringify(entry)};`);
		lines.push(`sink.push(${names.map((name) => `e${i}_${name}`).join(', ')});`);
		count += names.length;
	}

	lines.push('globalThis.__ceiling_sink = sink;');

	return { code: lines.join('\n') + '\n', count, skipped };
}

/**
 * @param {string} root
 * @param {{ include_dev?: boolean }} [options]
 */
export async function build_ceiling(root, { include_dev = false } = {}) {
	const exports_by_entry = await collect_exports(root);
	const skip = include_dev
		? new Set()
		: dev_exports(exports_by_entry.get('svelte/internal/client') ?? []);
	const { code, count, skipped } = generate_entry(exports_by_entry, skip);

	const entry = path.join(root, 'src/__ceiling.js');
	fs.writeFileSync(entry, code);

	try {
		await build({
			root,
			configFile: false,
			logLevel: 'error',
			plugins: [],
			build: {
				outDir: 'dist/ceiling',
				emptyOutDir: true,
				minify: 'esbuild',
				reportCompressedSize: false,
				rollupOptions: {
					input: entry,
					output: { entryFileNames: 'ceiling.js' }
				}
			}
		});
	} finally {
		fs.rmSync(entry, { force: true });
	}

	return {
		file: path.join(root, 'dist/ceiling/ceiling.js'),
		count,
		skipped,
		include_dev,
		exports_by_entry
	};
}
