import path from 'node:path';
import { build } from 'vite';

/**
 * Every client-side entry point svelte ships. Anything a compiled component or a user
 * module can pull in at runtime comes from one of these, so the union of their exports
 * bounds how large the svelte half of a client bundle can ever get.
 */
export const CLIENT_ENTRIES = [
	'svelte',
	'svelte/internal/client',
	'svelte/transition',
	'svelte/animate',
	'svelte/motion',
	'svelte/store',
	'svelte/reactivity',
	'svelte/reactivity/window',
	'svelte/easing',
	'svelte/legacy',
	'svelte/events',
	'svelte/attachments',
	'svelte/internal/disclose-version',
	'svelte/internal/flags/async',
	'svelte/internal/flags/legacy',
	'svelte/internal/flags/tracing'
];

const PREFIX = 'virtual:ceiling:';

/** @param {Record<string, string>} modules */
function virtual(modules) {
	return {
		name: 'ceiling-virtual',
		/** @param {string} id */
		resolveId: (id) => (id.startsWith(PREFIX) ? '\0' + id : null),
		/** @param {string} id */
		load: (id) => (id.startsWith('\0' + PREFIX) ? modules[id.slice(1)] : null)
	};
}

/**
 * Asks rollup what each entry point exports. Reading it back off the build output is
 * authoritative — parsing `index.js` by hand undercounts, because some names are
 * re-exported through chains the source text doesn't spell out.
 *
 * @param {string} root
 * @returns {Promise<Map<string, string[]>>}
 */
export async function collect_exports(root) {
	const modules = Object.fromEntries(
		CLIENT_ENTRIES.map((entry) => [PREFIX + entry, `export * from ${JSON.stringify(entry)};`])
	);

	const result = await build({
		root,
		configFile: false,
		logLevel: 'error',
		plugins: [virtual(modules)],
		build: {
			write: false,
			minify: false,
			rollupOptions: {
				input: Object.fromEntries(CLIENT_ENTRIES.map((e, i) => [`e${i}`, PREFIX + e])),
				preserveEntrySignatures: 'strict',
				output: { format: 'es' }
			}
		}
	});

	const output = (Array.isArray(result) ? result[0] : result).output;
	const map = new Map();

	for (const [i, entry] of CLIENT_ENTRIES.entries()) {
		const chunk = output.find((c) => c.type === 'chunk' && c.name === `e${i}`);
		map.set(
			entry,
			(chunk?.exports ?? []).filter((name) => name !== 'default')
		);
	}

	return map;
}

/**
 * Builds an entry module that references every export by name and leaks the lot to
 * `globalThis`, so rollup cannot drop any of it.
 *
 * Named imports rather than `import * as ns` on purpose: a namespace object that escapes
 * forces rollup to materialise the namespace itself, which adds ~5kB of property tables
 * that no real app would ever ship. Naming each binding keeps the bound tight.
 *
 * @param {Map<string, string[]>} exports_by_entry
 */
export function generate_entry(exports_by_entry) {
	const lines = [
		'// GENERATED by scripts/ceiling.js — do not edit.',
		'// Every export of every client-side svelte entry point, forced live.',
		'const sink = [];'
	];

	let count = 0;

	for (const [i, [entry, names]] of [...exports_by_entry].entries()) {
		if (names.length === 0) {
			lines.push(`import ${JSON.stringify(entry)}; // side-effect only`);
			continue;
		}
		// alias everything: entry points overlap, and raw names would collide
		const spec = names.map((name) => `${name} as e${i}_${name}`).join(', ');
		lines.push(`import { ${spec} } from ${JSON.stringify(entry)};`);
		lines.push(`sink.push(${names.map((name) => `e${i}_${name}`).join(', ')});`);
		count += names.length;
	}

	lines.push('globalThis.__ceiling_sink = sink;');

	return { code: lines.join('\n') + '\n', count };
}

/** @param {string} root */
export async function build_ceiling(root) {
	const exports_by_entry = await collect_exports(root);
	const { code, count } = generate_entry(exports_by_entry);

	const entry = path.join(root, 'src/__ceiling.js');
	const fs = await import('node:fs');
	fs.writeFileSync(entry, code);

	try {
		await build({
			root,
			configFile: false,
			logLevel: 'error',
			plugins: [],
			build: {
				outDir: 'dist/ceiling',
				emptyOutDir: true,
				minify: 'esbuild',
				reportCompressedSize: false,
				rollupOptions: {
					input: entry,
					output: { entryFileNames: 'ceiling.js' }
				}
			}
		});
	} finally {
		fs.rmSync(entry, { force: true });
	}

	return {
		file: path.join(root, 'dist/ceiling/ceiling.js'),
		count,
		exports_by_entry
	};
}
